name: Java CI - Lucee Latest v7

on: [push, pull_request,workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      luceeVersionQuery: 0/all/light
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: maven-cache
    - name: Cache Lucee files
      uses: actions/cache@v4
      with:
        path: _actions/lucee/script-runner/main/lucee-download-cache
        key: lucee-downloads
    - name: Build extension-openapi with Ant
      run: mvn clean package
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: openapi-lex
        path: target/*.lex
    - name: Checkout Lucee
      uses: actions/checkout@v4
      with:
        repository: lucee/lucee
        path: lucee
    - name: Run Lucee Test Suite, labels="openapi"
      uses: lucee/script-runner@main
      with:
        webroot: ${{ github.workspace }}/lucee/test
        execute: /bootstrap-tests.cfm
        luceeVersion: ${{ env.luceeVersion }}
        luceeVersionQuery: ${{ env.luceeVersionQuery }}
        extensionDir: ${{ github.workspace }}/dist
      env:
        testLabels: openapi
        testAdditional: ${{ github.workspace }}/tests
